/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NougaUiModule extends AbstractNougaUiModule {

	public NougaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
