/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga;

import org.eclipse.xtext.resource.DerivedStateAwareResource;
import org.eclipse.xtext.resource.DerivedStateAwareResourceDescriptionManager;
import org.eclipse.xtext.resource.IDerivedStateComputer;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.XtextResource;

import be.kuleuven.simoncockx.nouga.derivedstate.NougaDerivedStateComputer;
import be.kuleuven.simoncockx.nouga.generator.JavaExpressionUtil;
import be.kuleuven.simoncockx.nouga.generator.JavaLibUtil;
import be.kuleuven.simoncockx.nouga.generator.JavaNameUtil;
import be.kuleuven.simoncockx.nouga.generator.JavaTypeUtil;
import be.kuleuven.simoncockx.nouga.typing.TypeFactory;
import be.kuleuven.simoncockx.nouga.typing.TypeUtil;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NougaRuntimeModule extends AbstractNougaRuntimeModule {
	@Override
	public Class<? extends XtextResource> bindXtextResource() {
		return DerivedStateAwareResource.class;
	}
	public Class<? extends IDerivedStateComputer> bindIDerivedStateComputer() {
		return NougaDerivedStateComputer.class;
	}
	public Class<? extends IResourceDescription.Manager> bindIResourceDescriptionManager() {
		return DerivedStateAwareResourceDescriptionManager.class;
	}
	
	public Class<? extends TypeFactory> bindTypeFactory() {
		return TypeFactory.class;
	}
	public Class<? extends TypeUtil> bindTypeUtil() {
		return TypeUtil.class;
	}
	
	public Class<? extends JavaNameUtil> bindJavaNameUtil() {
		return JavaNameUtil.class;
	}
	public Class<? extends JavaTypeUtil> bindJavaTypeUtil() {
		return JavaTypeUtil.class;
	}
	public Class<? extends JavaExpressionUtil> bindJavaExpressionUtil() {
		return JavaExpressionUtil.class;
	}
	public Class<? extends JavaLibUtil> bindJavaLibUtil() {
		return JavaLibUtil.class;
	}
}
