/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NougaStandaloneSetup extends NougaStandaloneSetupGenerated {

	public static void doSetup() {
		new NougaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
