/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga.validation;

import be.kuleuven.simoncockx.nouga.typing.validation.NougaTypingValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class NougaValidator extends NougaTypingValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					NougaPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
