/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga.ide;

import be.kuleuven.simoncockx.nouga.NougaRuntimeModule;
import be.kuleuven.simoncockx.nouga.NougaStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NougaIdeSetup extends NougaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NougaRuntimeModule(), new NougaIdeModule()));
	}
	
}
