/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import com.google.inject.Inject;

import be.kuleuven.simoncockx.nouga.nouga.Type;
import be.kuleuven.simoncockx.nouga.nouga.Data;
import be.kuleuven.simoncockx.nouga.nouga.InstantiationExpression;
import be.kuleuven.simoncockx.nouga.nouga.DataType;
import be.kuleuven.simoncockx.nouga.nouga.Function;
import be.kuleuven.simoncockx.nouga.nouga.KeyValuePair;
import be.kuleuven.simoncockx.nouga.nouga.ListType;
import be.kuleuven.simoncockx.nouga.nouga.NougaPackage;
import be.kuleuven.simoncockx.nouga.nouga.ProjectionExpression;
import be.kuleuven.simoncockx.nouga.typing.NougaTyping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class NougaScopeProvider extends AbstractNougaScopeProvider {
	@Inject
	private NougaTyping typing;
	
	@Override
	public IScope getScope(EObject context, EReference reference) {
		if (context instanceof Data && reference == NougaPackage.Literals.DATA__PARENT) {
			EObject rootElement = EcoreUtil2.getRootContainer(context);
	        List<Data> candidates = EcoreUtil2.getAllContentsOfType(rootElement, Data.class);
	        return Scopes.scopeFor(candidates);
		} else if (context instanceof ProjectionExpression && reference == NougaPackage.Literals.PROJECTION_EXPRESSION__ATTRIBUTE) {
			ProjectionExpression ctx = (ProjectionExpression)context;
			ListType lt = ctx.getReceiver().getStaticType();
			if (lt != null) {
				Type type = ctx.getReceiver().getStaticType().getItemType();
				if (type instanceof DataType) {
					return Scopes.scopeFor(typing.allAttributes(((DataType)type).getData()));
				}
			}
			return IScope.NULLSCOPE;
		} else if (context instanceof Function && reference == NougaPackage.Literals.VARIABLE_REFERENCE__REFERENCE) {
			Function function = (Function)context;
			return Scopes.scopeFor(function.getInputs());
		} else if (context instanceof KeyValuePair && reference == NougaPackage.Literals.KEY_VALUE_PAIR__KEY) {
			InstantiationExpression instance = EcoreUtil2.getContainerOfType(context, InstantiationExpression.class);
			return Scopes.scopeFor(typing.allAttributes(instance.getType()));
		}
		return super.getScope(context, reference);
	}
}
