/*
 * generated by Xtext 2.25.0
 */
package be.kuleuven.simoncockx.nouga.tests

import be.kuleuven.simoncockx.nouga.nouga.Model
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(NougaInjectorProvider)
class NougaParsingTest {
	@Inject
	extension ParseHelper<Model> parseHelper
	@Inject
	extension ValidationTestHelper
	
	@Test
	def void loadModel() {
		'''
			namespace just.some.package
		'''.parse.assertNoErrors
	}
	
	@Test
	def void testNestedProjection() {
		'''
		    namespace dummypackage
		    
		    type A:
		      val int (1..1)
		    type B:
		      a A (1..1)
		    
		    func NestedProjection:
		      inputs: b B (1..1)
		      output: result int (1..1)
		      assign-output:
		        b -> a -> val
		'''.parse.assertNoErrors
	}
}